name: Build

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0']
        phpunit-versions: ['8.5.18']
        include:
        - operating-system: 'ubuntu-latest'
          php-versions: '7.4'
          phpunit-versions: '8.5.18'

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug
        tools: phpunit:${{ matrix.phpunit-versions }}

    - name: Install Composer dependencies
      run: |
        composer update
        composer install --dev --no-interaction

    - name: Test with phpunit
      run: vendor/bin/phpunit -c phpunit.xml.dist
